### ISSUE TITLE
what is the codename of Realme GT 5(8gen2）？

### ISSUE THREAD

**Issue by Boom-Hacker** [pjgowtham/android_device_realme_ferrarri#1]

**Comment by pjgowtham** [comment]
Need to know the prjname property value

adb shell getprop ro.boot.prjname

**Comment by Boom-Hacker** [comment]
then catch it from the kernel dtb sources?

**Comment by Boom-Hacker** [comment]
i compared all codenames in kernel sources.all name has related a phone,except the zonda.so i think it's "zonda"

**Comment by pjgowtham** [comment]
You can grep prjname onto kernel dtb source to find what codename it is.
